### ISSUE TITLE
Why not more general solution?

### ISSUE THREAD

**Issue by ghost** [slurps-mad-rips/byteswap#1]
```
template <typename T>
void SwapBytes(T& var)
{
	std::span<std::byte> buffer{reinterpret_cast<std::byte*>(&var), sizeof(var)};
	std::reverse(std::begin(buffer), std::end(buffer));
}
```

This is what I use inside [my serialization library](https://gitlab.com/ftz/serialization) (sans std::span because it's not in libstdc++ yet). For standardization I think the only thing left is to write a proper concept for `T`.

Here are, again, stuff from my lib:

```
template <typename T>
concept bool TriviallySerializable()
{
	return std::is_arithmetic_v<T> || std::is_enum_v<T>;
}

template <typename T>
concept bool TriviallyDeserializable()
{
	return std::is_arithmetic_v<T> || std::is_same_v<T, std::byte>;
}
```

**Comment by bruxisma** [comment]
Hi. byteswap as it's currently designed mimics existing intrinsics (as the committee's focus is to standardize existing practice. Additionally, your implementation is not `constexpr`.

**Comment by ghost** [comment]
You can use overloading to implement intrinsics.
